use_frameworks!

target 'SwiftyTinder_Example' do
  pod 'SwiftyTinder', :path => '../'

  target 'SwiftyTinder_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
